name: vizor
description: A new Flutter package project.
version: 0.0.1
author: vizor-ui
homepage: https://github.com/vizor-ui/vizor

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  soundpool: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sounds/
